// <auto-generated />
namespace Abp.NServiceBus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NServiceBus_Schema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NServiceBus_Schema));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131425514_NServiceBus_Schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
